name: Auto merge

on:
  schedule:
    - cron: '0 0-23 * * *'

jobs:
  trigger-master-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'develop'
          development_branch: 'master'
          allow_ff: true
          ff_only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
