name: E2E
on: push
jobs:
  linux:
    name: E2E

    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: ['12']

    runs-on: ${{ matrix.os }}

    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

    steps:
      - name: Checkout branch
        uses: actions/checkout@master

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        uses: djp3/puppeteer-headful@master
        with:
          args: yarn test

  window-and-maxos:
    name: E2E

    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest']
        node: ['12']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@master

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test
